server:
  port: 26001
eureka:
  instance:
    hostname: lsdn-screen-logic
  client:
    serviceUrl:
      defaultZone: http://lsdn-registry:24001/eureka/
spring:
  application:
    name: lsdn-screen-logic
  data:
    rest:
      defaultMediaType: application/json
  jackson:
    serialization:
      INDENT_OUTPUT: true
  cloud:
    refresh:
      extra-refreshable: none
tx-lcn:
  client:
    manager-address: 172.16.50.141:8070